/**
 * WhatsApp calling: the control plane.
 *
 * Meta signals calls as ordinary webhooks on the `calls` field, and every
 * action taken on a call is a POST to the same Graph endpoint the app
 * already uses for messages. That half is exactly like the rest of this
 * codebase and is what lives here.
 *
 * **The half that is not here, and why.** Answering a call requires an
 * SDP *answer* generated by a real WebRTC stack — Meta's documentation is
 * explicit that the offer must not be echoed back — and then a live
 * DTLS/SRTP media session for as long as the call lasts. Node has no
 * WebRTC of its own, and a persistent real-time media process is a
 * different kind of infrastructure from anything else this app runs. So
 * `acceptCall` takes an SDP answer rather than inventing one: whatever
 * produces the media — an in-process WebRTC library, or a SIP endpoint
 * if that route is taken later — hands it in.
 *
 * The consequence is worth stating plainly rather than discovering: until
 * something supplies that answer, a call can be rejected, terminated,
 * recorded in history and rung to an agent, but not picked up.
 */

const META_API_VERSION = 'v21.0'
const META_API_BASE = `https://graph.facebook.com/${META_API_VERSION}`

/** What Meta reports about a call, normalised to this app's vocabulary. */
export type CallWebhookEvent =
  /** Someone is calling. Carries the offer that must be answered. */
  | { kind: 'connect'; callId: string; from: string; to: string; sdp: string | null; timestamp: Date }
  /** The call ended, by either side or by Meta. */
  | { kind: 'terminate'; callId: string; status: string | null; durationSeconds: number | null; timestamp: Date }
  /** Anything else Meta adds later — recorded, not guessed at. */
  | { kind: 'other'; callId: string | null; event: string; timestamp: Date }

/** True when this webhook change is about calls rather than messages. */
export function isCallWebhookField(field: string): boolean {
  return field === 'calls'
}

interface RawCall {
  id?: string
  call_id?: string
  from?: string
  to?: string
  event?: string
  direction?: string
  status?: string
  timestamp?: string | number
  duration?: number
  session?: { sdp?: string; sdp_type?: string }
  connection?: { webrtc?: { sdp?: string } }
}

/**
 * Reads Meta's call payload without assuming one exact shape.
 *
 * Deliberately tolerant. The field names here come from documentation
 * and third-party write-ups rather than from a call observed on this
 * account, and a call arriving in a slightly different shape should be
 * logged and stored, never dropped — an unrecognised call still rang
 * somebody's phone.
 */
export function parseCallWebhook(value: unknown): CallWebhookEvent[] {
  const calls = (value as { calls?: RawCall[] })?.calls
  if (!Array.isArray(calls)) return []

  return calls.map((call): CallWebhookEvent => {
    const callId = call.id ?? call.call_id ?? null
    const event = (call.event ?? call.status ?? '').toLowerCase()
    const timestamp = parseTimestamp(call.timestamp)

    if (event === 'connect' && callId) {
      return {
        kind: 'connect',
        callId,
        from: call.from ?? '',
        to: call.to ?? '',
        sdp: call.session?.sdp ?? call.connection?.webrtc?.sdp ?? null,
        timestamp,
      }
    }

    if ((event === 'terminate' || event === 'terminated') && callId) {
      return {
        kind: 'terminate',
        callId,
        status: call.status ?? null,
        durationSeconds: typeof call.duration === 'number' ? call.duration : null,
        timestamp,
      }
    }

    return { kind: 'other', callId, event: event || 'unknown', timestamp }
  })
}

/** Meta sends seconds; Date wants milliseconds. A missing or unreadable
 *  timestamp becomes now rather than 1970, which would sort a live call
 *  to the bottom of the history. */
function parseTimestamp(value: string | number | undefined): Date {
  if (value === undefined) return new Date()
  const n = typeof value === 'number' ? value : Number(value)
  if (!Number.isFinite(n) || n <= 0) return new Date()
  return new Date(n * 1000)
}

interface CallActionArgs {
  phoneNumberId: string
  accessToken: string
  callId: string
}

async function postCallAction(
  args: CallActionArgs & { action: string; extra?: Record<string, unknown> },
): Promise<{ ok: boolean; error?: string }> {
  const res = await fetch(`${META_API_BASE}/${args.phoneNumberId}/calls`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${args.accessToken}`,
    },
    body: JSON.stringify({
      messaging_product: 'whatsapp',
      call_id: args.callId,
      action: args.action,
      ...args.extra,
    }),
  })

  if (res.ok) return { ok: true }

  // Read as text first: an error from Meta is not guaranteed to be JSON,
  // and letting the parse throw would replace a real status with a
  // parser complaint — the same trap already hit elsewhere in this app.
  const raw = await res.text().catch(() => '')
  let message = `HTTP ${res.status}`
  try {
    const parsed = JSON.parse(raw) as { error?: { message?: string } }
    if (parsed.error?.message) message = parsed.error.message
  } catch {
    if (raw) message = raw.slice(0, 300)
  }
  return { ok: false, error: message }
}

/**
 * Signals that the call is being answered before the answer itself is
 * ready. Meta uses it to start setting up media sooner, which is the
 * difference between a caller hearing a greeting promptly and hearing
 * two seconds of nothing first. Optional — skipping it costs latency,
 * not correctness.
 */
export function preAcceptCall(args: CallActionArgs & { sdpAnswer: string }) {
  return postCallAction({
    ...args,
    action: 'pre_accept',
    extra: { session: { sdp_type: 'answer', sdp: args.sdpAnswer } },
  })
}

/**
 * Answers the call.
 *
 * `sdpAnswer` must come from a real WebRTC stack that is prepared to
 * carry the media. Meta's own documentation warns against echoing back
 * the offer, and a fabricated answer fails at DTLS rather than at this
 * call — which would look like a call that connected and then went
 * silent, the hardest possible thing to debug.
 */
export function acceptCall(args: CallActionArgs & { sdpAnswer: string }) {
  return postCallAction({
    ...args,
    action: 'accept',
    extra: { session: { sdp_type: 'answer', sdp: args.sdpAnswer } },
  })
}

/** Declines without answering. The caller hears it as declined. */
export function rejectCall(args: CallActionArgs) {
  return postCallAction({ ...args, action: 'reject' })
}

/** Hangs up a call that was answered. */
export function terminateCall(args: CallActionArgs) {
  return postCallAction({ ...args, action: 'terminate' })
}

/**
 * Calls a customer.
 *
 * Only reaches someone who has granted call permission — Meta enforces
 * that, so a refusal here is usually consent rather than a fault.
 */
export async function initiateCall(args: {
  phoneNumberId: string
  accessToken: string
  to: string
  sdpOffer: string
}): Promise<{ ok: boolean; callId?: string; error?: string }> {
  const res = await fetch(`${META_API_BASE}/${args.phoneNumberId}/calls`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${args.accessToken}`,
    },
    body: JSON.stringify({
      messaging_product: 'whatsapp',
      to: args.to,
      action: 'connect',
      session: { sdp_type: 'offer', sdp: args.sdpOffer },
    }),
  })

  const raw = await res.text().catch(() => '')
  let parsed: { calls?: { id: string }[]; error?: { message?: string } } = {}
  try {
    parsed = JSON.parse(raw)
  } catch {
    /* handled below */
  }

  if (!res.ok) {
    return { ok: false, error: parsed.error?.message ?? raw.slice(0, 300) ?? `HTTP ${res.status}` }
  }
  return { ok: true, callId: parsed.calls?.[0]?.id }
}
