'use client'

import { useRef, useState } from 'react'
import { Download, Upload, CheckCircle2, AlertCircle, Loader2, Database, ShieldAlert } from 'lucide-react'
import { Button } from '@/components/ui/button'

type Status = 'idle' | 'loading' | 'success' | 'error'

function SectionCard({ title, description, icon: Icon, tone = 'indigo', children }: {
  title: string
  description: React.ReactNode
  icon: React.ElementType
  tone?: 'indigo' | 'rose'
  children: React.ReactNode
}) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden">
      <div className="px-6 py-4 border-b border-slate-100 flex items-start gap-3">
        <span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${
          tone === 'rose' ? 'bg-rose-50' : 'bg-[#EEF0FF]'
        }`}>
          <Icon className={`h-4.5 w-4.5 ${tone === 'rose' ? 'text-rose-600' : 'text-[#5B6CF9]'}`} />
        </span>
        <div className="flex-1 min-w-0">
          <h3 className="text-[14px] font-semibold text-slate-800">{title}</h3>
          <p className="text-[12px] text-slate-500 mt-0.5 leading-relaxed">{description}</p>
        </div>
      </div>
      <div className="px-6 py-5 space-y-4">{children}</div>
    </div>
  )
}

export function DatabasePanel() {
  const fileRef = useRef<HTMLInputElement>(null)

  const [backupStatus, setBackupStatus] = useState<Status>('idle')
  const [backupError, setBackupError] = useState<string | null>(null)

  const [restoreStatus, setRestoreStatus] = useState<Status>('idle')
  const [restoreError, setRestoreError] = useState<string | null>(null)
  const [restoreLog, setRestoreLog] = useState<string | null>(null)
  const [confirmRestore, setConfirmRestore] = useState(false)
  const [pendingFile, setPendingFile] = useState<File | null>(null)

  // ── Backup ────────────────────────────────────────────────────
  const handleBackup = async () => {
    setBackupStatus('loading')
    setBackupError(null)
    try {
      const res = await fetch('/api/database/backup')
      if (!res.ok) {
        const body = await res.json() as { error?: string }
        throw new Error(body.error ?? `HTTP ${res.status}`)
      }
      const blob = await res.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      const cd = res.headers.get('Content-Disposition')
      const match = cd?.match(/filename="([^"]+)"/)
      a.download = match?.[1] ?? `crm-db-backup-${new Date().toISOString().slice(0, 10)}.sql`
      a.href = url
      a.click()
      URL.revokeObjectURL(url)
      setBackupStatus('success')
      setTimeout(() => setBackupStatus('idle'), 4000)
    } catch (err) {
      setBackupError(err instanceof Error ? err.message : 'Backup failed')
      setBackupStatus('error')
    }
  }

  // ── Restore — step 1: pick file ───────────────────────────────
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return
    if (!file.name.endsWith('.sql')) {
      setRestoreError('Please select a .sql file generated by the backup tool.')
      setRestoreStatus('error')
      if (fileRef.current) fileRef.current.value = ''
      return
    }
    setPendingFile(file)
    setConfirmRestore(true)
    setRestoreStatus('idle')
    setRestoreError(null)
    setRestoreLog(null)
    if (fileRef.current) fileRef.current.value = ''
  }

  // ── Restore — step 2: confirmed ───────────────────────────────
  const executeRestore = async () => {
    if (!pendingFile) return
    setConfirmRestore(false)
    setRestoreStatus('loading')
    setRestoreError(null)
    setRestoreLog(null)

    try {
      const formData = new FormData()
      formData.append('file', pendingFile)

      const res = await fetch('/api/database/restore', {
        method: 'POST',
        body: formData,
      })

      const body = await res.json() as { ok?: boolean; error?: string; log?: string }

      if (!res.ok || !body.ok) {
        setRestoreError(body.error ?? 'Restore failed')
        setRestoreLog(body.log ?? null)
        setRestoreStatus('error')
      } else {
        setRestoreLog(body.log ?? null)
        setRestoreStatus('success')
      }
    } catch (err) {
      setRestoreError(err instanceof Error ? err.message : 'Unknown error')
      setRestoreStatus('error')
    } finally {
      setPendingFile(null)
    }
  }

  const cancelRestore = () => {
    setPendingFile(null)
    setConfirmRestore(false)
  }

  return (
    <div className="space-y-5">

      {/* Backup card */}
      <SectionCard
        title="PostgreSQL Backup"
        icon={Download}
        description={<>Downloads a complete <code className="text-[11px] bg-slate-100 px-1 py-0.5 rounded">.sql</code> dump
          of the entire database using <code className="text-[11px] bg-slate-100 px-1 py-0.5 rounded">pg_dump</code>.
          Includes all tables, data, and schema.</>}
      >
        <Button
          onClick={handleBackup}
          disabled={backupStatus === 'loading'}
          className="h-9 px-4 text-[13px] bg-[#5B6CF9] hover:bg-[#4a5ce8] text-white gap-2"
        >
          {backupStatus === 'loading' ? (
            <><Loader2 className="h-4 w-4 animate-spin" />Preparing dump…</>
          ) : backupStatus === 'success' ? (
            <><CheckCircle2 className="h-4 w-4" />Downloaded!</>
          ) : (
            <><Download className="h-4 w-4" />Download Database Backup</>
          )}
        </Button>

        {backupStatus === 'error' && (
          <p className="flex items-center gap-1.5 text-[12.5px] text-rose-600">
            <AlertCircle className="h-4 w-4 shrink-0" />
            {backupError}
          </p>
        )}

        <div className="rounded-xl bg-slate-50 border border-slate-100 p-3.5 text-[12px] text-slate-500 flex items-start gap-2 leading-relaxed">
          <Database className="h-4 w-4 shrink-0 mt-0.5 text-slate-400" />
          <span>
            The backup is a plain SQL file generated with{' '}
            <code className="text-[11px] bg-slate-100 px-1 rounded">pg_dump --clean --if-exists</code>.
            It can be restored here or manually with <code className="text-[11px] bg-slate-100 px-1 rounded">psql</code>.
          </span>
        </div>
      </SectionCard>

      {/* Restore card */}
      <SectionCard
        title="Restore Database"
        icon={Upload}
        tone="rose"
        description={<>Upload a <code className="text-[11px] bg-slate-100 px-1 py-0.5 rounded">.sql</code> backup file to restore the database.
          Uses <code className="text-[11px] bg-slate-100 px-1 py-0.5 rounded">psql</code> in a single transaction — rolls back on error.</>}
      >
        <div className="rounded-xl bg-amber-50 border border-amber-200 p-3.5 flex items-start gap-2.5 text-[12px] text-amber-800 leading-relaxed">
          <ShieldAlert className="h-4 w-4 shrink-0 mt-0.5 text-amber-500" />
          <span>
            <strong>Destructive operation.</strong> The backup file contains <code className="text-[11px] bg-amber-100 px-1 rounded">DROP TABLE</code> statements
            that will replace all existing data. Only owners can perform a restore.
            Download a fresh backup first if you want to preserve current data.
          </span>
        </div>

        <div className="flex items-center gap-3">
          <input
            ref={fileRef}
            type="file"
            accept=".sql,application/sql,text/plain"
            className="hidden"
            onChange={handleFileChange}
          />
          <Button
            variant="outline"
            className="h-9 px-4 text-[13px] gap-2 border-rose-200 text-rose-600 hover:bg-rose-50"
            onClick={() => fileRef.current?.click()}
            disabled={restoreStatus === 'loading' || confirmRestore}
          >
            {restoreStatus === 'loading' ? (
              <><Loader2 className="h-4 w-4 animate-spin" />Restoring…</>
            ) : (
              <><Upload className="h-4 w-4" />Upload &amp; Restore .sql File</>
            )}
          </Button>
        </div>

        {/* Confirm dialog */}
        {confirmRestore && pendingFile && (
          <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 space-y-3">
            <p className="text-[13px] font-medium text-slate-800">
              Are you sure you want to restore from{' '}
              <span className="font-semibold">{pendingFile.name}</span>?
            </p>
            <p className="text-[12.5px] text-slate-500 leading-relaxed">
              This will drop and recreate all database tables. All current data will be replaced
              with the backup contents. This cannot be undone.
            </p>
            <div className="flex gap-2">
              <Button
                size="sm"
                className="h-8 text-[12.5px] gap-1.5 bg-rose-600 hover:bg-rose-700 text-white"
                onClick={executeRestore}
              >
                <Upload className="h-3.5 w-3.5" />
                Yes, restore now
              </Button>
              <Button size="sm" variant="outline" className="h-8 text-[12.5px] border-slate-200" onClick={cancelRestore}>
                Cancel
              </Button>
            </div>
          </div>
        )}

        {/* Success */}
        {restoreStatus === 'success' && (
          <div className="space-y-2">
            <p className="flex items-center gap-1.5 text-[12.5px] text-emerald-600 font-medium">
              <CheckCircle2 className="h-4 w-4" />
              Database restored successfully.
            </p>
            {restoreLog && (
              <pre className="text-[11px] bg-slate-50 border border-slate-100 rounded-xl p-3 overflow-auto max-h-40 text-slate-500">
                {restoreLog}
              </pre>
            )}
          </div>
        )}

        {/* Error */}
        {restoreStatus === 'error' && (
          <div className="space-y-2">
            <p className="flex items-center gap-1.5 text-[12.5px] text-rose-600 font-medium">
              <AlertCircle className="h-4 w-4 shrink-0" />
              {restoreError ?? 'Restore failed'}
            </p>
            {restoreLog && (
              <pre className="text-[11px] bg-slate-50 border border-slate-100 rounded-xl p-3 overflow-auto max-h-40 text-slate-500">
                {restoreLog}
              </pre>
            )}
          </div>
        )}
      </SectionCard>

      {/* Manual restore instructions */}
      <SectionCard
        title="Manual Restore (CLI)"
        icon={Database}
        description="You can also restore the backup directly from a terminal."
      >
        <pre className="text-[11px] bg-slate-50 border border-slate-100 rounded-xl p-3.5 overflow-auto text-slate-500 leading-relaxed">
{`# Restore to the same database
psql -h HOST -U USER -d DATABASE -f crm-db-backup-YYYY-MM-DD.sql

# Or restore to a fresh database
createdb -h HOST -U USER new_crm_db
psql -h HOST -U USER -d new_crm_db -f crm-db-backup-YYYY-MM-DD.sql`}
        </pre>
      </SectionCard>
    </div>
  )
}
