'use client'

import { useRef, useState } from 'react'
import { Download, Upload, CheckCircle2, AlertCircle, Loader2, Database, ShieldAlert } from 'lucide-react'
import { Button } from '@/components/ui/button'

type Status = 'idle' | 'loading' | 'success' | 'error'

export function DatabasePanel() {
  const fileRef = useRef<HTMLInputElement>(null)

  const [backupStatus, setBackupStatus] = useState<Status>('idle')
  const [backupError, setBackupError] = useState<string | null>(null)

  const [restoreStatus, setRestoreStatus] = useState<Status>('idle')
  const [restoreError, setRestoreError] = useState<string | null>(null)
  const [restoreLog, setRestoreLog] = useState<string | null>(null)
  const [confirmRestore, setConfirmRestore] = useState(false)
  const [pendingFile, setPendingFile] = useState<File | null>(null)

  // ── Backup ────────────────────────────────────────────────────
  const handleBackup = async () => {
    setBackupStatus('loading')
    setBackupError(null)
    try {
      const res = await fetch('/api/database/backup')
      if (!res.ok) {
        const body = await res.json() as { error?: string }
        throw new Error(body.error ?? `HTTP ${res.status}`)
      }
      const blob = await res.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      const cd = res.headers.get('Content-Disposition')
      const match = cd?.match(/filename="([^"]+)"/)
      a.download = match?.[1] ?? `crm-db-backup-${new Date().toISOString().slice(0, 10)}.sql`
      a.href = url
      a.click()
      URL.revokeObjectURL(url)
      setBackupStatus('success')
      setTimeout(() => setBackupStatus('idle'), 4000)
    } catch (err) {
      setBackupError(err instanceof Error ? err.message : 'Backup failed')
      setBackupStatus('error')
    }
  }

  // ── Restore — step 1: pick file ───────────────────────────────
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return
    if (!file.name.endsWith('.sql')) {
      setRestoreError('Please select a .sql file generated by the backup tool.')
      setRestoreStatus('error')
      if (fileRef.current) fileRef.current.value = ''
      return
    }
    setPendingFile(file)
    setConfirmRestore(true)
    setRestoreStatus('idle')
    setRestoreError(null)
    setRestoreLog(null)
    if (fileRef.current) fileRef.current.value = ''
  }

  // ── Restore — step 2: confirmed ───────────────────────────────
  const executeRestore = async () => {
    if (!pendingFile) return
    setConfirmRestore(false)
    setRestoreStatus('loading')
    setRestoreError(null)
    setRestoreLog(null)

    try {
      const formData = new FormData()
      formData.append('file', pendingFile)

      const res = await fetch('/api/database/restore', {
        method: 'POST',
        body: formData,
      })

      const body = await res.json() as { ok?: boolean; error?: string; log?: string }

      if (!res.ok || !body.ok) {
        setRestoreError(body.error ?? 'Restore failed')
        setRestoreLog(body.log ?? null)
        setRestoreStatus('error')
      } else {
        setRestoreLog(body.log ?? null)
        setRestoreStatus('success')
      }
    } catch (err) {
      setRestoreError(err instanceof Error ? err.message : 'Unknown error')
      setRestoreStatus('error')
    } finally {
      setPendingFile(null)
    }
  }

  const cancelRestore = () => {
    setPendingFile(null)
    setConfirmRestore(false)
  }

  return (
    <div className="space-y-6">

      {/* Backup card */}
      <div className="rounded-xl border border-slate-200 bg-white p-6 space-y-4">
        <div className="flex items-start gap-3">
          <div className="rounded-lg bg-primary/10 p-2 mt-0.5">
            <Download className="size-5 text-primary" />
          </div>
          <div className="flex-1">
            <h3 className="font-semibold text-slate-800">PostgreSQL Backup</h3>
            <p className="text-sm text-slate-500 mt-0.5">
              Downloads a complete <code className="text-xs bg-slate-100 px-1 py-0.5 rounded">.sql</code> dump
              of the entire database using <code className="text-xs bg-slate-100 px-1 py-0.5 rounded">pg_dump</code>.
              Includes all tables, data, and schema.
            </p>
          </div>
        </div>

        <Button
          onClick={handleBackup}
          disabled={backupStatus === 'loading'}
          className="gap-2"
        >
          {backupStatus === 'loading' ? (
            <><Loader2 className="size-4 animate-spin" />Preparing dump…</>
          ) : backupStatus === 'success' ? (
            <><CheckCircle2 className="size-4" />Downloaded!</>
          ) : (
            <><Download className="size-4" />Download Database Backup</>
          )}
        </Button>

        {backupStatus === 'error' && (
          <p className="flex items-center gap-1.5 text-sm text-destructive">
            <AlertCircle className="size-4 shrink-0" />
            {backupError}
          </p>
        )}

        <div className="rounded-lg bg-slate-100 border border-slate-200 p-3 text-sm text-slate-500 flex items-start gap-2">
          <Database className="size-4 shrink-0 mt-0.5" />
          <span>
            The backup is a plain SQL file generated with{' '}
            <code className="text-xs bg-slate-100 px-1 rounded">pg_dump --clean --if-exists</code>.
            It can be restored here or manually with <code className="text-xs bg-slate-100 px-1 rounded">psql</code>.
          </span>
        </div>
      </div>

      {/* Restore card */}
      <div className="rounded-xl border border-slate-200 bg-white p-6 space-y-4">
        <div className="flex items-start gap-3">
          <div className="rounded-lg bg-destructive/10 p-2 mt-0.5">
            <Upload className="size-5 text-destructive" />
          </div>
          <div className="flex-1">
            <h3 className="font-semibold text-slate-800">Restore Database</h3>
            <p className="text-sm text-slate-500 mt-0.5">
              Upload a <code className="text-xs bg-slate-100 px-1 py-0.5 rounded">.sql</code> backup file to restore the database.
              Uses <code className="text-xs bg-slate-100 px-1 py-0.5 rounded">psql</code> in a single transaction — rolls back on error.
            </p>
          </div>
        </div>

        <div className="rounded-lg bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 p-3 flex items-start gap-2.5 text-sm text-amber-800 dark:text-amber-300">
          <ShieldAlert className="size-4 shrink-0 mt-0.5" />
          <span>
            <strong>Destructive operation.</strong> The backup file contains <code className="text-xs bg-amber-100 dark:bg-amber-900 px-1 rounded">DROP TABLE</code> statements
            that will replace all existing data. Only owners can perform a restore.
            Download a fresh backup first if you want to preserve current data.
          </span>
        </div>

        <div className="flex items-center gap-3">
          <input
            ref={fileRef}
            type="file"
            accept=".sql,application/sql,text/plain"
            className="hidden"
            onChange={handleFileChange}
          />
          <Button
            variant="outline"
            className="gap-2 border-destructive text-destructive hover:bg-destructive/10"
            onClick={() => fileRef.current?.click()}
            disabled={restoreStatus === 'loading' || confirmRestore}
          >
            {restoreStatus === 'loading' ? (
              <><Loader2 className="size-4 animate-spin" />Restoring…</>
            ) : (
              <><Upload className="size-4" />Upload & Restore .sql File</>
            )}
          </Button>
        </div>

        {/* Confirm dialog */}
        {confirmRestore && pendingFile && (
          <div className="rounded-lg border border-destructive/40 bg-destructive/5 p-4 space-y-3">
            <p className="text-sm font-medium text-slate-800">
              Are you sure you want to restore from{' '}
              <span className="font-semibold">{pendingFile.name}</span>?
            </p>
            <p className="text-sm text-slate-500">
              This will drop and recreate all database tables. All current data will be replaced
              with the backup contents. This cannot be undone.
            </p>
            <div className="flex gap-2">
              <Button
                size="sm"
                className="gap-1.5 bg-destructive hover:bg-destructive/90"
                onClick={executeRestore}
              >
                <Upload className="size-3.5" />
                Yes, restore now
              </Button>
              <Button size="sm" variant="outline" onClick={cancelRestore}>
                Cancel
              </Button>
            </div>
          </div>
        )}

        {/* Success */}
        {restoreStatus === 'success' && (
          <div className="space-y-2">
            <p className="flex items-center gap-1.5 text-sm text-emerald-600 font-medium">
              <CheckCircle2 className="size-4" />
              Database restored successfully.
            </p>
            {restoreLog && (
              <pre className="text-xs bg-slate-100 rounded-lg p-3 overflow-auto max-h-40 text-slate-500">
                {restoreLog}
              </pre>
            )}
          </div>
        )}

        {/* Error */}
        {restoreStatus === 'error' && (
          <div className="space-y-2">
            <p className="flex items-center gap-1.5 text-sm text-destructive font-medium">
              <AlertCircle className="size-4 shrink-0" />
              {restoreError ?? 'Restore failed'}
            </p>
            {restoreLog && (
              <pre className="text-xs bg-slate-100 rounded-lg p-3 overflow-auto max-h-40 text-slate-500">
                {restoreLog}
              </pre>
            )}
          </div>
        )}
      </div>

      {/* Manual restore instructions */}
      <div className="rounded-xl border border-slate-200 bg-white p-6 space-y-3">
        <h3 className="font-semibold text-slate-800 text-sm">Manual Restore (CLI)</h3>
        <p className="text-sm text-slate-500">
          You can also restore the backup directly from a terminal:
        </p>
        <pre className="text-xs bg-slate-100 rounded-lg p-3 overflow-auto text-slate-500 leading-relaxed">
{`# Restore to the same database
psql -h HOST -U USER -d DATABASE -f crm-db-backup-YYYY-MM-DD.sql

# Or restore to a fresh database
createdb -h HOST -U USER new_crm_db
psql -h HOST -U USER -d new_crm_db -f crm-db-backup-YYYY-MM-DD.sql`}
        </pre>
      </div>
    </div>
  )
}
